Update psalm.yml
Signed-off-by: Joas Schilling <213943+nickvergessen@users.noreply.github.com>

diff --git a/.github/workflows/psalm.yml b/.github/workflows/psalm.yml
--- a/.github/workflows/psalm.yml
+++ b/.github/workflows/psalm.yml
@@ -5,13 +5,7 @@
 
 name: Static analysis
 
-on:
-  pull_request:
-  push:
-    branches:
-      - master
-      - main
-      - stable*
+on: pull_request
 
 concurrency: 
   group: psalm-${{ github.head_ref || github.run_id }}
@@ -19,21 +13,41 @@ concurrency:
 
 jobs:
   static-analysis:
+      runs-on: ubuntu-latest
+      strategy:
+          # do not stop on another job's failure
+          fail-fast: false
+          matrix:
+              ocp-version: [ 'dev-master', 'dev-stable25', 'dev-stable24', 'dev-stable23' ]
+      name: Nextcloud ${{ matrix.ocp-version }}
+      steps:
+          - name: Checkout
+            uses: actions/checkout@v3
+
+          - name: Set up php
+            uses: shivammathur/setup-php@v2
+            with:
+                php-version: 7.4
+                tools: composer:v1
+                coverage: none
+
+          - name: Install dependencies
+            run: composer i
+
+          - name: Install dependencies
+            run: composer require --dev nextcloud/ocp:${{ matrix.ocp-version }} --ignore-platform-reqs
+
+          - name: Run coding standards check
+            run: composer run psalm
+
+  summary:
     runs-on: ubuntu-latest
+    needs: static-analysis
 
-    name: Nextcloud
+    if: always()
+
+    name: static-psalm-analysis-summary
+
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-
-      - name: Set up php
-        uses: shivammathur/setup-php@v2
-        with:
-          php-version: 7.4
-          coverage: none
-
-      - name: Install dependencies
-        run: composer i
-
-      - name: Run coding standards check
-        run: composer run psalm
+      - name: Summary status
+        run: if ${{ needs.static-analysis.result != 'success' }}; then exit 1; fi
